FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/ubuntu:22.04-linuxarm64

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /workspace

# Install etcd、haproxy and nc (nc for health check)
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends haproxy netcat-openbsd && \
    apt-get clean && \
    rm -rf /var/cache/apt/* && \
    rm -rf /var/lib/apt/lists/*

# Copy scripts of haproxy
RUN mkdir -p /home/ma-user

COPY . /home/ma-user/haproxy

CMD ["/bin/bash"]
